name: Rust

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    

env:
  CARGO_TERM_COLOR: always

jobs:
  create_log_dir:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: mkdir
      run: mkdir -p ${{ github.workspace }}/logs
    
  build:
    needs: create_log_dir
    runs-on: ubuntu-latest
    strategy:
      matrix:
        prefix: 
          - 
          - "lib."
        value:
          - lib
          - rlib
          - dylib
          - cdylib
          - staticlib
    steps:
    - name: build with string
      run: >-
        echo "----------build ${{matrix.prefix}}crate-type = ${{matrix.value}}----------" > ${{ github.workspace }}/${{matrix.prefix}}${{matrix.value}}.txt &&
        rm -rf ./target/ &&
        cargo build --lib --release --config '${{matrix.prefix}}crate-type = "${{matrix.value}}"' &&
        ls ./target/release/ >> ${{ github.workspace }}/${{matrix.prefix}}${{matrix.value}}.txt &&
        echo "------------------------------" >> ${{ github.workspace }}/${{matrix.prefix}}${{matrix.value}}.txt
    - name: build with array
      run: >-
        echo "----------build ${{matrix.prefix}}crate-type = [${matrix.value}]----------" >> ${{ github.workspace }}/${{matrix.prefix}}${{matrix.value}}.txt &&
        rm -rf ./target/ &&
        cargo build --lib --release --config '${{matrix.prefix}}crate-type = [${{matrix.value}}]' &&
        ls ./target/release/ >> ${{ github.workspace }}/${{matrix.prefix}}${{matrix.value}}.txt &&
        echo "------------------------------" >> ${{ github.workspace }}/${{matrix.prefix}}${{matrix.value}}.txt
    - uses: actions/upload-artifact@v3
      with:
        name: ${{matrix.prefix}}${{matrix.value}}.txt
        path: ${{ github.workspace }}/${{matrix.prefix}}${{matrix.value}}.txt
    - name: print output
      run: cat ${{ github.workspace }}/${{matrix.prefix}}${{matrix.value}}.txt
